/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIdRouteImport } from './routes/projects/$id'
import { Route as OrgSlugRouteImport } from './routes/org/$slug'
import { Route as InviteInvitationIdRouteImport } from './routes/invite/$invitationId'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as ApiProjectsRouteImport } from './routes/api/projects'
import { Route as ApiOrganizationsRouteImport } from './routes/api/organizations'
import { Route as ApiInviteRouteImport } from './routes/api/invite'
import { Route as ProjectsIdIndexRouteImport } from './routes/projects/$id.index'
import { Route as OrgSlugIndexRouteImport } from './routes/org/$slug.index'
import { Route as ProjectsIdApiKeysRouteImport } from './routes/projects/$id.api-keys'
import { Route as OrgSlugNewProjectRouteImport } from './routes/org/$slug.new-project'
import { Route as ApiRunsIdRouteImport } from './routes/api/runs/$id'
import { Route as ApiProjectsIdRouteImport } from './routes/api/projects/$id'
import { Route as ApiInviteIdRouteImport } from './routes/api/invite/$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ProjectsIdRunsRunIdRouteImport } from './routes/projects/$id/runs/$runId'
import { Route as ApiRunsIdDiffRouteImport } from './routes/api/runs/$id/diff'
import { Route as ApiProjectsIdApiKeyRouteImport } from './routes/api/projects/$id/api-key'
import { Route as ApiInviteIdAcceptRouteImport } from './routes/api/invite/$id/accept'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSlugRoute = OrgSlugRouteImport.update({
  id: '/org/$slug',
  path: '/org/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteInvitationIdRoute = InviteInvitationIdRouteImport.update({
  id: '/invite/$invitationId',
  path: '/invite/$invitationId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsRoute = ApiProjectsRouteImport.update({
  id: '/api/projects',
  path: '/api/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrganizationsRoute = ApiOrganizationsRouteImport.update({
  id: '/api/organizations',
  path: '/api/organizations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInviteRoute = ApiInviteRouteImport.update({
  id: '/api/invite',
  path: '/api/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdIndexRoute = ProjectsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsIdRoute,
} as any)
const OrgSlugIndexRoute = OrgSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrgSlugRoute,
} as any)
const ProjectsIdApiKeysRoute = ProjectsIdApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => ProjectsIdRoute,
} as any)
const OrgSlugNewProjectRoute = OrgSlugNewProjectRouteImport.update({
  id: '/new-project',
  path: '/new-project',
  getParentRoute: () => OrgSlugRoute,
} as any)
const ApiRunsIdRoute = ApiRunsIdRouteImport.update({
  id: '/api/runs/$id',
  path: '/api/runs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsIdRoute = ApiProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiProjectsRoute,
} as any)
const ApiInviteIdRoute = ApiInviteIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiInviteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdRunsRunIdRoute = ProjectsIdRunsRunIdRouteImport.update({
  id: '/runs/$runId',
  path: '/runs/$runId',
  getParentRoute: () => ProjectsIdRoute,
} as any)
const ApiRunsIdDiffRoute = ApiRunsIdDiffRouteImport.update({
  id: '/diff',
  path: '/diff',
  getParentRoute: () => ApiRunsIdRoute,
} as any)
const ApiProjectsIdApiKeyRoute = ApiProjectsIdApiKeyRouteImport.update({
  id: '/api-key',
  path: '/api-key',
  getParentRoute: () => ApiProjectsIdRoute,
} as any)
const ApiInviteIdAcceptRoute = ApiInviteIdAcceptRouteImport.update({
  id: '/accept',
  path: '/accept',
  getParentRoute: () => ApiInviteIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/invite': typeof ApiInviteRouteWithChildren
  '/api/organizations': typeof ApiOrganizationsRoute
  '/api/projects': typeof ApiProjectsRouteWithChildren
  '/api/upload': typeof ApiUploadRoute
  '/invite/$invitationId': typeof InviteInvitationIdRoute
  '/org/$slug': typeof OrgSlugRouteWithChildren
  '/projects/$id': typeof ProjectsIdRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/invite/$id': typeof ApiInviteIdRouteWithChildren
  '/api/projects/$id': typeof ApiProjectsIdRouteWithChildren
  '/api/runs/$id': typeof ApiRunsIdRouteWithChildren
  '/org/$slug/new-project': typeof OrgSlugNewProjectRoute
  '/projects/$id/api-keys': typeof ProjectsIdApiKeysRoute
  '/org/$slug/': typeof OrgSlugIndexRoute
  '/projects/$id/': typeof ProjectsIdIndexRoute
  '/api/invite/$id/accept': typeof ApiInviteIdAcceptRoute
  '/api/projects/$id/api-key': typeof ApiProjectsIdApiKeyRoute
  '/api/runs/$id/diff': typeof ApiRunsIdDiffRoute
  '/projects/$id/runs/$runId': typeof ProjectsIdRunsRunIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/invite': typeof ApiInviteRouteWithChildren
  '/api/organizations': typeof ApiOrganizationsRoute
  '/api/projects': typeof ApiProjectsRouteWithChildren
  '/api/upload': typeof ApiUploadRoute
  '/invite/$invitationId': typeof InviteInvitationIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/invite/$id': typeof ApiInviteIdRouteWithChildren
  '/api/projects/$id': typeof ApiProjectsIdRouteWithChildren
  '/api/runs/$id': typeof ApiRunsIdRouteWithChildren
  '/org/$slug/new-project': typeof OrgSlugNewProjectRoute
  '/projects/$id/api-keys': typeof ProjectsIdApiKeysRoute
  '/org/$slug': typeof OrgSlugIndexRoute
  '/projects/$id': typeof ProjectsIdIndexRoute
  '/api/invite/$id/accept': typeof ApiInviteIdAcceptRoute
  '/api/projects/$id/api-key': typeof ApiProjectsIdApiKeyRoute
  '/api/runs/$id/diff': typeof ApiRunsIdDiffRoute
  '/projects/$id/runs/$runId': typeof ProjectsIdRunsRunIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/invite': typeof ApiInviteRouteWithChildren
  '/api/organizations': typeof ApiOrganizationsRoute
  '/api/projects': typeof ApiProjectsRouteWithChildren
  '/api/upload': typeof ApiUploadRoute
  '/invite/$invitationId': typeof InviteInvitationIdRoute
  '/org/$slug': typeof OrgSlugRouteWithChildren
  '/projects/$id': typeof ProjectsIdRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/invite/$id': typeof ApiInviteIdRouteWithChildren
  '/api/projects/$id': typeof ApiProjectsIdRouteWithChildren
  '/api/runs/$id': typeof ApiRunsIdRouteWithChildren
  '/org/$slug/new-project': typeof OrgSlugNewProjectRoute
  '/projects/$id/api-keys': typeof ProjectsIdApiKeysRoute
  '/org/$slug/': typeof OrgSlugIndexRoute
  '/projects/$id/': typeof ProjectsIdIndexRoute
  '/api/invite/$id/accept': typeof ApiInviteIdAcceptRoute
  '/api/projects/$id/api-key': typeof ApiProjectsIdApiKeyRoute
  '/api/runs/$id/diff': typeof ApiRunsIdDiffRoute
  '/projects/$id/runs/$runId': typeof ProjectsIdRunsRunIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/api/invite'
    | '/api/organizations'
    | '/api/projects'
    | '/api/upload'
    | '/invite/$invitationId'
    | '/org/$slug'
    | '/projects/$id'
    | '/api/auth/$'
    | '/api/invite/$id'
    | '/api/projects/$id'
    | '/api/runs/$id'
    | '/org/$slug/new-project'
    | '/projects/$id/api-keys'
    | '/org/$slug/'
    | '/projects/$id/'
    | '/api/invite/$id/accept'
    | '/api/projects/$id/api-key'
    | '/api/runs/$id/diff'
    | '/projects/$id/runs/$runId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/api/invite'
    | '/api/organizations'
    | '/api/projects'
    | '/api/upload'
    | '/invite/$invitationId'
    | '/api/auth/$'
    | '/api/invite/$id'
    | '/api/projects/$id'
    | '/api/runs/$id'
    | '/org/$slug/new-project'
    | '/projects/$id/api-keys'
    | '/org/$slug'
    | '/projects/$id'
    | '/api/invite/$id/accept'
    | '/api/projects/$id/api-key'
    | '/api/runs/$id/diff'
    | '/projects/$id/runs/$runId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/api/invite'
    | '/api/organizations'
    | '/api/projects'
    | '/api/upload'
    | '/invite/$invitationId'
    | '/org/$slug'
    | '/projects/$id'
    | '/api/auth/$'
    | '/api/invite/$id'
    | '/api/projects/$id'
    | '/api/runs/$id'
    | '/org/$slug/new-project'
    | '/projects/$id/api-keys'
    | '/org/$slug/'
    | '/projects/$id/'
    | '/api/invite/$id/accept'
    | '/api/projects/$id/api-key'
    | '/api/runs/$id/diff'
    | '/projects/$id/runs/$runId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ApiInviteRoute: typeof ApiInviteRouteWithChildren
  ApiOrganizationsRoute: typeof ApiOrganizationsRoute
  ApiProjectsRoute: typeof ApiProjectsRouteWithChildren
  ApiUploadRoute: typeof ApiUploadRoute
  InviteInvitationIdRoute: typeof InviteInvitationIdRoute
  OrgSlugRoute: typeof OrgSlugRouteWithChildren
  ProjectsIdRoute: typeof ProjectsIdRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRunsIdRoute: typeof ApiRunsIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/$slug': {
      id: '/org/$slug'
      path: '/org/$slug'
      fullPath: '/org/$slug'
      preLoaderRoute: typeof OrgSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$invitationId': {
      id: '/invite/$invitationId'
      path: '/invite/$invitationId'
      fullPath: '/invite/$invitationId'
      preLoaderRoute: typeof InviteInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects': {
      id: '/api/projects'
      path: '/api/projects'
      fullPath: '/api/projects'
      preLoaderRoute: typeof ApiProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/organizations': {
      id: '/api/organizations'
      path: '/api/organizations'
      fullPath: '/api/organizations'
      preLoaderRoute: typeof ApiOrganizationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/invite': {
      id: '/api/invite'
      path: '/api/invite'
      fullPath: '/api/invite'
      preLoaderRoute: typeof ApiInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id/': {
      id: '/projects/$id/'
      path: '/'
      fullPath: '/projects/$id/'
      preLoaderRoute: typeof ProjectsIdIndexRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/org/$slug/': {
      id: '/org/$slug/'
      path: '/'
      fullPath: '/org/$slug/'
      preLoaderRoute: typeof OrgSlugIndexRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/projects/$id/api-keys': {
      id: '/projects/$id/api-keys'
      path: '/api-keys'
      fullPath: '/projects/$id/api-keys'
      preLoaderRoute: typeof ProjectsIdApiKeysRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/org/$slug/new-project': {
      id: '/org/$slug/new-project'
      path: '/new-project'
      fullPath: '/org/$slug/new-project'
      preLoaderRoute: typeof OrgSlugNewProjectRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/api/runs/$id': {
      id: '/api/runs/$id'
      path: '/api/runs/$id'
      fullPath: '/api/runs/$id'
      preLoaderRoute: typeof ApiRunsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects/$id': {
      id: '/api/projects/$id'
      path: '/$id'
      fullPath: '/api/projects/$id'
      preLoaderRoute: typeof ApiProjectsIdRouteImport
      parentRoute: typeof ApiProjectsRoute
    }
    '/api/invite/$id': {
      id: '/api/invite/$id'
      path: '/$id'
      fullPath: '/api/invite/$id'
      preLoaderRoute: typeof ApiInviteIdRouteImport
      parentRoute: typeof ApiInviteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id/runs/$runId': {
      id: '/projects/$id/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/projects/$id/runs/$runId'
      preLoaderRoute: typeof ProjectsIdRunsRunIdRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/api/runs/$id/diff': {
      id: '/api/runs/$id/diff'
      path: '/diff'
      fullPath: '/api/runs/$id/diff'
      preLoaderRoute: typeof ApiRunsIdDiffRouteImport
      parentRoute: typeof ApiRunsIdRoute
    }
    '/api/projects/$id/api-key': {
      id: '/api/projects/$id/api-key'
      path: '/api-key'
      fullPath: '/api/projects/$id/api-key'
      preLoaderRoute: typeof ApiProjectsIdApiKeyRouteImport
      parentRoute: typeof ApiProjectsIdRoute
    }
    '/api/invite/$id/accept': {
      id: '/api/invite/$id/accept'
      path: '/accept'
      fullPath: '/api/invite/$id/accept'
      preLoaderRoute: typeof ApiInviteIdAcceptRouteImport
      parentRoute: typeof ApiInviteIdRoute
    }
  }
}

interface ApiInviteIdRouteChildren {
  ApiInviteIdAcceptRoute: typeof ApiInviteIdAcceptRoute
}

const ApiInviteIdRouteChildren: ApiInviteIdRouteChildren = {
  ApiInviteIdAcceptRoute: ApiInviteIdAcceptRoute,
}

const ApiInviteIdRouteWithChildren = ApiInviteIdRoute._addFileChildren(
  ApiInviteIdRouteChildren,
)

interface ApiInviteRouteChildren {
  ApiInviteIdRoute: typeof ApiInviteIdRouteWithChildren
}

const ApiInviteRouteChildren: ApiInviteRouteChildren = {
  ApiInviteIdRoute: ApiInviteIdRouteWithChildren,
}

const ApiInviteRouteWithChildren = ApiInviteRoute._addFileChildren(
  ApiInviteRouteChildren,
)

interface ApiProjectsIdRouteChildren {
  ApiProjectsIdApiKeyRoute: typeof ApiProjectsIdApiKeyRoute
}

const ApiProjectsIdRouteChildren: ApiProjectsIdRouteChildren = {
  ApiProjectsIdApiKeyRoute: ApiProjectsIdApiKeyRoute,
}

const ApiProjectsIdRouteWithChildren = ApiProjectsIdRoute._addFileChildren(
  ApiProjectsIdRouteChildren,
)

interface ApiProjectsRouteChildren {
  ApiProjectsIdRoute: typeof ApiProjectsIdRouteWithChildren
}

const ApiProjectsRouteChildren: ApiProjectsRouteChildren = {
  ApiProjectsIdRoute: ApiProjectsIdRouteWithChildren,
}

const ApiProjectsRouteWithChildren = ApiProjectsRoute._addFileChildren(
  ApiProjectsRouteChildren,
)

interface OrgSlugRouteChildren {
  OrgSlugNewProjectRoute: typeof OrgSlugNewProjectRoute
  OrgSlugIndexRoute: typeof OrgSlugIndexRoute
}

const OrgSlugRouteChildren: OrgSlugRouteChildren = {
  OrgSlugNewProjectRoute: OrgSlugNewProjectRoute,
  OrgSlugIndexRoute: OrgSlugIndexRoute,
}

const OrgSlugRouteWithChildren =
  OrgSlugRoute._addFileChildren(OrgSlugRouteChildren)

interface ProjectsIdRouteChildren {
  ProjectsIdApiKeysRoute: typeof ProjectsIdApiKeysRoute
  ProjectsIdIndexRoute: typeof ProjectsIdIndexRoute
  ProjectsIdRunsRunIdRoute: typeof ProjectsIdRunsRunIdRoute
}

const ProjectsIdRouteChildren: ProjectsIdRouteChildren = {
  ProjectsIdApiKeysRoute: ProjectsIdApiKeysRoute,
  ProjectsIdIndexRoute: ProjectsIdIndexRoute,
  ProjectsIdRunsRunIdRoute: ProjectsIdRunsRunIdRoute,
}

const ProjectsIdRouteWithChildren = ProjectsIdRoute._addFileChildren(
  ProjectsIdRouteChildren,
)

interface ApiRunsIdRouteChildren {
  ApiRunsIdDiffRoute: typeof ApiRunsIdDiffRoute
}

const ApiRunsIdRouteChildren: ApiRunsIdRouteChildren = {
  ApiRunsIdDiffRoute: ApiRunsIdDiffRoute,
}

const ApiRunsIdRouteWithChildren = ApiRunsIdRoute._addFileChildren(
  ApiRunsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ApiInviteRoute: ApiInviteRouteWithChildren,
  ApiOrganizationsRoute: ApiOrganizationsRoute,
  ApiProjectsRoute: ApiProjectsRouteWithChildren,
  ApiUploadRoute: ApiUploadRoute,
  InviteInvitationIdRoute: InviteInvitationIdRoute,
  OrgSlugRoute: OrgSlugRouteWithChildren,
  ProjectsIdRoute: ProjectsIdRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRunsIdRoute: ApiRunsIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
